
import domain.BarcodeController;
import domain.Leverancier;
import domain.Product;
import gui.StartScherm;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javafx.application.Application;
import javafx.stage.Stage;
import javax.persistence.EntityManager;
import javax.swing.JFrame;
import persistentie.JPAUtil;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thomas
 */
public class StartUp extends Application{
    @Override
    public void start(Stage stage) throws SQLException, IllegalStateException, ClassNotFoundException, IOException {
        BarcodeController domeinController = new BarcodeController();
        StartScherm test = new StartScherm(domeinController);
        test.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        test.setSize(1100,800);
        test.setVisible(true);

        //WAT IS ER AL GEBEURD:
        //DE LIJSTEN MET DE INGESCANDE PRODUCTEN KAN JE ZIEN SAMEN MET DE STANDAARD INGESTELDE LEVERANCIER
        //ALS HET PRODUCT NOG GEEN LEVERANCIER HEEFT DAN STAAT ER "GEEN LEVERANCIER"
        //LATER ZOU HET DE BEDOELING ZIJN OM GEEN BESTELLING TE KUNNEN MAKEN ZONDER DAT ALLE "GEEN LEVERANCIER" MELDINGEN WEG ZIJN
        //ALS DE GEBRUIKER KLIKT OP DE "GEEN LEVERANCIER" MOET HIJ EEN SECTIE KRIJGEN WAAR HIJ DE STANDAARLEVERANCIER KAN INSTELLEN
        //ALS HET PRODUCT NOG GEEN LEVERANCIER HEEFT DAN KRIJGT HET DE MELDING: ER ZIJN NOG GEEN BARCODES VAN LEVERANCIERS VOOR DIT PRODUCT
        //U MOET EEN BARCODE TOEVOEGEN: MET ERONDER EEN KNOP VOEG BARCODE TOE.
        //DE BARCODE DIE DAN WORDT AANGEMAAKT WORDT OOK AUTOMATISCH DE STANDAARDLEVERANCIER
        //ALS HET PRODUCT WEL AL LEVERANCIERS HEEFT IN DE DATABASE DAN KAN HET ERUIT KIEZEN IN EEN COMBOBOX (NIET VEEL WERK INSTEKEN, WORDT ZOGOED ALS NIET GEBRUIKT)
        //DAT GELDT OOK ALLEMAAL ALS JE KLIKT OP EEN PRODUCT MET EEN LEVERANCIER. ALS HET PRODUCT MAAR 1 LEVERANCIER KENT EN HIJ KLIKT ER OP DAN KRIJGT
        //HET DE MELDING OF HIJ ER NOG 1 WIL TOEVOEGEN, ALS DE GEBRUIKER OP "JA" KLIKT DAN KRIJGT HIJ EEN SCHERM WAAR HIJ DE BARCODE VAN EEN LEVERANCIER KAN INGEVEN
        //DAARNA KRIJGT HIJ EEN SCHERM WAAR HIJ KAN KIEZEN WAT DE STANDAARLEVERANCIER WORDT, ALS HET HETZELFDE BLIJFT MOET DE GEBRUIKER ENKEL OP DE KNOP DUWEN
        
        //DAT ZOUDEN DE VOLGENDE DINGEN ZIJN DIE MOETEN GEBEUREN
        //VEEL SUCCES!
        
        //UPDATE 7/07/2015
        //KIEZEN VAN STANDAARDLEVERANCIER IS AANGEMAAKT
        //NOG NIET OP FOUTVERWERKING OFZO GEDACHT OF GEKEKEN!!
        //HIJ PAST DE LIJST NOG NIET DIRECT AAN! EENS GOED BEKIJKEN MET DIE NOTIFYOBSERVERS!!
        
        //UPDATE 9/07/2015
        //IK DENK DAT HET HET BESTE IS DAT WANNEER HET PROGRAMMA WORDT AFGESLOTEN DAT ALLE WIJZIGINGEN VAN DE GESCANDE PRODUCTEN WORDEN OPGESLAGEN IN DE DATABANK!!
        //OOK FUNCTIONALITEIT VOORZIEN OM EEN NIEUW SET VAN PRODUCTEN TERUG IN TE SCANNEN! OOK PRODUCTEN IN DE LIJST VERWIJDEREN OF TOEVOEGEN VIA BARCODE!
        //TOEVOEGEN VAN BARCODE WERKT, DE FUNCTIONALITEIT ALLESZINS, DE LIJST UPDATE OOK VANZICHZELF WAT WEL REDELIJK TOF IS!
        //MISSCHIEN EERSTE EENS DE GUI PERFECT ZETTEN ZODAT WE VERDER KUNNEN MET EEN DEFTIGE GUI
        //VOOR DE SCHIKKING VAN COMPONENTEN IN DE JPANEL HEB IK AL WAT GEPROBEERD MET WAT BOXMENUFLOWSHIT, ZEKER NOG EENS BEKIJKEN
        //VANAF GUI KLAAR IS DAN OOK EENS KIJKEN VOOR WAT VALIDATIE!
        
        //UPDATE 15/07/2015
        //REDELIJK WAT FUNCTIONALITEITEN BIJGESCHREVEN
        //COMBOBOXPROBLEEM IS WEGGEWERKT
        //NIEUWE LIST ERINGESTOKEN VOOR DE AANTALLEN
        //WAS NODIG
        
        //VOOR DE VOLGENDE KEER: 
        //BESTELSCHERM AL LATEN WERKEN
        //GUI WAT OPSCHONEN!
        
        //WAT AAN DE GUI GEWERKT
        //DE PANELS MOETEN WEL NOG DYNAMISCH WORDEN TOEGEVOEGD!
        //DIT IS BLIJKBAAR MET REVALIDATE() MAAR HET WERKT NOG NIET!
        
        //3/08/2015
        //EENS NAKIJKEN OMDAT DE LIJSTEN NIET MEER AUTOMATISCH AANPASSEN
        //HET VOLGENDE DAT MOET GEDAAN WORDEN IS HET TOEVOEGEN EN VERWIJDEREN VAN EEN LEVERANCIER
        //OOK EENS NADENKEN OVER HET VERWIJDEREN VAN EEN LEVERANCIER WAT JE DAN MOET DOEN MET DE PRODUCTEN DIE DIE LEVERANCIER GEKOZEN HEEFT
        //DAN KIJKEN WAAR EN WANNEER BEPAALDE KNOPPEN MOETEN TEVOORSCHIJN KOMEN
        
        //05/08/2015
        //VANAF DAT EEN LEVERANCIER WORDT VERWIJDERT MOETEN DE PRODUCTEN AANGEPAST WORDEN
        //DE PRODUCTEN DIE DAN 2 LEVERANCIERS HEBBEN MOET DAN DEGENE DIE NIET VERWIJDERT WORDT
        //ALS STANDAARDLEVERANCIER INGESTELD WORDEN
        //BIJ MEER DAN 2 MOET DE EERST VOLGENDE ALS STANDAAR WORDEN INGESTELD OF MOET DE GEBRUIKER DE KEUZE KRIJGEN OM EEN STANDAARD TE SELECTEREN TUSSEN DIE 2
        
        //LET OP FUNCTIONALITEIT BIJ VERWIJDEREN VAN EEN LEVERANCIER, HEEFT NOG REDELIJK WAT WERK NODIG!

        //VOOR DE VOLGENDE KEER KAN AL BEGONNEN WORDEN AAN DE VALIDATIE
        //TOEVOEGEN VAN EEN BESTAAND PRODUCT WERKT AL VOLLEDIG!
        
        //LAYOUT AANGEPAST, VOLGENDE KEER ALLE FUNCTIONALITEITEN TESTEN EN VALIDATIE SCHRIJVEN
        //FUNCTIONALITEITEN PER PRIORITEIT:
        //AFDRUKKEN LIJST(EN) MET PRODUCTEN MET OVEREENKOMSTIGE LEVERANCIERSBARCODENUMMER PER LEVERANCIER MET DE OVEREENKOMSTIGE AANTALLEN
        //VERANDEREN VAN BESTELLEVERANCIER
        //TOEVOEGEN VAN EEN LEVERANCIER
        //VERWIJDEREN VAN EEN LEVERANCIER
        //MOGELIJKHEID OM EEN NIEUWE SCAN UIT TE VOEREN ZONDER PROGRAMMA AF TE SLUITEN
        //OMSCHRIJVING EN ANDERE DETAILS VAN PRODUCT AANPASSEN
        //AANTAL VAN BESTELLING WIJZIGEN IN PROGRAMMA (BIJ DETAILS VAN PRODUCT)
        //TOEVOEGEN VAN EEN NIEUW PRODUCT MET OMSCHRIJVING EN EIGEN BARCODE
        //TOEVOEGEN EN VERWIJDEREN VAN PRODUCT IN LIJST VAN INGESCANDE PRODUCTEN
        //VERWIJDEREN VAN EEN NIEUW PRODUCT 
        
        //niet elke leverancier heeft barcode bij een product
//        Scene scene = new Scene(new StartFrame(domeinController));
//        stage.setTitle("Menu");
//        stage.setScene(scene);
//        stage.sizeToScene();
//
//        // The stage will not get smaller than its preferred (initial) size.
//        stage.setOnShown((WindowEvent t) -> {
//            stage.setMinWidth(stage.getWidth());
//            stage.setMinHeight(stage.getHeight());
//        });
//        stage.show();
    }

    public static void main(String... args) {
        Application.launch(StartUp.class, args);
    }

}
